### ISSUE TITLE
Help with the regex

### ISSUE THREAD

**Issue by alextakitani** [mchelem/terminator-editor-plugin#16]
Hi! Thank you so much for this plugin, save me a lot of work! 

I'm trying to make it work with files with or without line numbers, have tried you examples but couldn't make it work.

Do you have a working example of something that would caught 

/home/test.b:30
/home/test.b
/home/test

I'm still trying but I'm only got it working partially.

Thanks!

**Comment by mchelem** [comment]
Hi @alextakitani! I'm glad to know the plugin is helping your work flow :)

From what you wrote, it looks like you would like to match anything besides white spaces, so I would add an alternative for when no line number is present:

```
(\S+?):(?:([0-9]+)|(?:.+))
```
If a line number is present, the plugin works as usual. When it's not available, it will use the part after the "|", meaning it will accept anything but will not use the text after the ":". This is achieved through the use of [non-capturing groups](https://docs.python.org/3/howto/regex.html#non-capturing-and-named-groups) (:?...).

In spite of the non-capturing groups, Terminator still underlines the whole line, so this may be confusing. Also, using a regex that is so general may underline things that are not files, so you may want to refine the expression a little to meet your needs. For example, should the path always contain a slash?

Please let me know if that solves the problem for you.
