### ISSUE TITLE
I can't enable EditorPlugin in Preferences -> Plugins

### ISSUE THREAD

**Issue by ciembor** [mchelem/terminator-editor-plugin#17]
I downloaded the plugin and I can see it in my terminator preferences. Hovewer when I try to enable it, it's the only one which doesn't change to enabled after clicking a checkbox.

Here is traceback:

```
Traceback (most recent call last):
  File "/usr/share/terminator/terminatorlib/prefseditor.py", line 1364, in on_plugin_toggled
    self.registry.enable(plugin)
  File "/usr/share/terminator/terminatorlib/plugin.py", line 142, in enable
    self.instances[plugin] = self.available_plugins[plugin]()
  File "/home/maciej/.config/terminator/plugins/editor_plugin.py", line 34, in __init__
    self.match = self.match.decode('string_escape')
AttributeError: 'str' object has no attribute 'decode'
```
`terminator 1.91`
`Ubuntu 19.04`
```
[~]$ python -V
Python 2.7.16
```
```
[~]$ python3 -V
Python 3.7.3
```

**Comment by mchelem** [comment]
@ciembor I checked Ubuntu's 19.04 release of Terminator 1.91 and it now runs on Python3. That means the string is already decoded. My simple fix (without going into checking which Python version is running) was just to see if the function exists on the match object before calling it. With the regular expressions I normally use it worked well. If you have the time to test, please let me know if you find any issues with the default decoding.

**Comment by edljk** [comment]
I had a similar issue when switching from Ubuntu 18.04 to 20.04: it was not possible to enable the plugin after clicking the checkbox.
This step is now ok with the new version but the plugin does not seem to be active: no hyperlinks in terminator..

```
terminator 1.91
[~]$ python3 -V
Python 3.8.2
```

**Comment by mchelem** [comment]
@edljk It's actually an issue with Terminator and It breaks all the URL handler plugins: https://bugs.launchpad.net/terminator/+bug/1867746

Terminator uses a deprecated VTE regex API and it was finally phased out: https://gitlab.gnome.org/GNOME/vte/issues/218
