### ISSUE TITLE
License change ?

### ISSUE THREAD

**Issue by amigrave** [mchelem/terminator-editor-plugin#9]
Hi Michele,

Could you please consider a license change to a more liberal one such as MIT or BSD so people can embbed your plugin in their dotfiles repository without having to use git submodules ?

**Comment by mchelem** [comment]
Hi there!

Would you please let me know exactly why the [GPLv2](https://tldrlegal.com/license/gnu-general-public-license-v2) doesn't fit your needs?

As far as I understand, you can distribute the plugin using GPL v2, so you could include it in your dotfiles repo.

**Comment by amigrave** [comment]
My concern is more about the fact of including your GPLv2 `editor_plugin.py` file into a MIT licensed project such as a dotfiles repo. I'm not a license expert but I've [read](http://stackoverflow.com/a/3903472/1968124) some [sources](http://programmers.stackexchange.com/questions/257115/components-having-gpl-and-mit-bsd-license-but-released-under-mit-license) stating it was not permitted by the GPLv2 unless you change the license of the host project. Am I wrong ?

**Comment by fotanus** [comment]
Hi there, IANAL but let me join this laws conversation :-)

To include GPLv2 code on your repository you can simply change your dotfiles permissions to GPLv2. You can't relicense a software that you didn't wrote, however you can sometimes change the license while redistributing. You can take an MIT software and redistribute it as GPL. However you can't redistribute GPL as MIT.

@amigrave Any specific reasons why you don't like GPL? [Here is a motivacional post to use it](https://www.gnu.org/philosophy/open-source-misses-the-point.html). GPL is good because it forces maintaining the software free, which don't means you can't make money with it, or even imply that you need to redistribute your code.

**Comment by amigrave** [comment]
> To include GPLv2 code on your repository you can simply change your dotfiles permissions to GPLv2.

which I don't want to do

> However you can't redistribute GPL as MIT.

yeps, this is what I read.

> @amigrave Any specific reasons why you don't like GPL?

The GPL is cluttered with politics and as a true gentlemen I don't talk about politic nor religion :-)

I just think that the GPL is not a suitable license for a 90 lines file whose usage is to be placed in users dotfiles (especially when we consider that a lot of those users will use an unlicensed or MIT repository in order to keep track of their dotfiles).

I guess the only workaround is to use git submodules which I didn't intended to use.

**Comment by fotanus** [comment]
Maybe I'm getting too old, but I find talk about politics be an important thing. I don't think it is likely someone sue you for having a gpl plugin on your mit repository. You think the same, don't you? And yet you decided to open this issue. 

I'm really curious to know why you don't want to license your dotfiles repo as GPL. I can see you have learn about GPL, so ignorance or it being too complicated don't seems like a proper answer. I can't think on a reason to not use GPL, unless you have written your own plugins directly on your dot files repository. 

Note: I'm not the code owner. I'm just curious.

**Comment by amigrave** [comment]
> Maybe I'm getting too old, but I find talk about politics be an important thing.
The complete phrase should have been that I don't talk about politic nor religion **in public space**.

Anyway, I just read the GPL faq and it's clear that the GPL prevent plugins of a GPL application to be licensed with another license. So I close this issue because even if she wanted to, the author cannot license this project otherwise. This is one more reason why I prefer LGPL over GPL.

Anyway, please accept my apologies for the noise I caused and have a nice day.
